[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = false

# Mantle network configuration
[rpc_endpoints]
Mantle-sepolia = "https://forno.Mantle-sepolia.Mantle-testnet.org/"
Mantle = "https://rpc.sepolia.mantle.xyz"

[etherscan]
Mantle = { key = "${ETHERSCAN_API_KEY}", url = "https://api.Mantlescan.io/api" }
Mantle-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://Mantle-sepolia.blockscout.com/api", verifier = "blockscout" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
